name: Empty
on: [push]
jobs:
  Appwrite-CLI:
    runs-on: ubuntu-latest
    steps:
      - uses: appwrite/setup-for-actions@feat-update-for-new-cli
        with:
          endpoint: '<your endpoint>'
          project: '<your project id>'
          key: '<your api key>'          
      - run: appwrite help
      
